version: '2'
services:
  app:
    container_name: loopback4-mongo
    restart: always
    build: ./
    ports:
      - '80:3000'
    volumes:
      - .:/app
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
